### ISSUE TITLE
Notify?

### ISSUE THREAD

**Issue by khusseini** [valiton/payum-payone#1]
Hello there,

I am currently using your repository with some minor modifications. I was wondering at what point the NotifyAction is executed? I have implemented the Credit card checkout but I alwyas get stuck in a pending status, although the preAuthorization was approved. For some reason the NotifyAction is never called. Can you help out?

**Comment by fjbender** [comment]
You'd probably need to set the "TransactionStatus URL" in the PMI (Merchant Backend) to your NotifyAction endpoint. If you need any assistance, the BS Payone Tech Support team might be able to help you.

**Comment by khusseini** [comment]
Ah yes, thank you. I wasn't aware that the notification comes from outside. I though it would be just a request to their server and getting directly a response back.
I'll check with the Tech Support team. Thank you

**Comment by khusseini** [comment]
Sorry to bother again. In my application I can only find two routes for the notify action:
```
payum_notify_do_unsafe                                                 ANY        ANY      ANY    /payment/notify/unsafe/{gateway}               
  payum_notify_do                                                        ANY        ANY      ANY    /payment/notify/{payum_token}       
```
Either of them are parametrized, how would I set the TransactionStatus URL there?

**Comment by naucon** [comment]
Hi,
payum provides for a non-dynamic notify URL the `payum_notify_do_unsafe` route. That takes a parameter `gateway` instead of the dynamic token. 

`/payment/notify/unsafe/{gateway}`

For PAYONE the gateway would be `payone`.

`/payment/notify/unsafe/payone`

**Comment by naucon** [comment]
Added a notice to the README, how to add a tranaction status url to the PMI.

ec63046d520b333c0a8b7a271360dd40318c17dc
